child_meal=float(input("What is the price of a child's meal? "))
child_drinks=float(input("What is the price for a child's drink? "))
adult_meal=float(input("What is the price of an adult's meal? "))
adult_drinks=float(input("What is the price for a adults drink? "))
children=int(input("How many children are there? "))
adults=int(input("How many adults are there? "))
tax=float(input("What is the sales tax rate? "))
print()# This is to print a blank space
subtotal=((child_meal) * (child_drinks) * (children) + (adult_meal) * (adult_drinks) * (adults))
print("Subtotal: {:.2f}".format(subtotal))
print(f"Subtotal: ${subtotal * 100 / 100.0}")
sales_tax=((subtotal) * (tax/100))
print("Sales_tax: {:.2f}".format(sales_tax))
print("sales_tax: ${sales_tax}")
total=((subtotal) + (sales_tax))
print("Total: {:.2f}".format(total))
print(f"total: ${total}")